# Generated by Django 3.0.4 on 2020-03-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200320_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
